# Generated by Django 3.1.2 on 2020-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_desc', models.TextField(max_length=100)),
                ('image_one', models.ImageField(default='', upload_to='About/images')),
                ('topic_one', models.CharField(max_length=50)),
                ('topic_title', models.CharField(max_length=50)),
                ('topic_desc', models.TextField(max_length=1000)),
                ('image_two', models.ImageField(default='', upload_to='About/images')),
                ('section', models.CharField(max_length=50)),
                ('section_two', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('subject', models.CharField(default='', max_length=80)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MoreAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
