# Generated by Django 3.1.1 on 2020-09-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogcate',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='cateid',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
