# Generated by Django 3.1.1 on 2020-09-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Site',
        ),
    ]
