# Generated by Django 3.1.2 on 2020-10-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('good_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
                ('name', models.TextField(max_length=200)),
                ('company_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vehicle_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('carry_weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_status', models.CharField(max_length=20)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.driver')),
                ('dst_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trip', to='truck_service.city')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.good')),
                ('src_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='truck_service.city')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.user')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.user'),
        ),
    ]
