# Generated by Django 3.1.2 on 2020-10-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truck_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='good_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_qty',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(default='2020-02-20 12:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='lbh_rem',
            field=models.DecimalField(decimal_places=3, default=5000.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='w_rem',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Good_Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.good')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truck_service.trip')),
            ],
        ),
    ]
