# Generated by Django 3.1.6 on 2021-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck_service', '0002_auto_20201014_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='FormTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.RemoveField(
            model_name='good',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='good_trip',
            name='good_id',
        ),
        migrations.RemoveField(
            model_name='good_trip',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dst_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='src_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='vehicle_id',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Good',
        ),
        migrations.DeleteModel(
            name='Good_Trip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
